# API Configuration
api:
  alpha_vantage:
    key: "N7GJYAZ1QOILRIFM"
    base_url: "https://www.alphavantage.co/query"
    call_limit_per_minute: 5
  
  news_api:
    key: "YOUR_NEWS_API_KEY"
    base_url: "https://newsapi.org/v2/"

# Database Configuration
database:
  type: "sqlite"  # Options: "sqlite", "mongodb"
  sqlite:
    path: "data/market_mind.db"
  mongodb:
    uri: "mongodb://localhost:27017/"
    db_name: "market_mind"

# Data Parameters
data:
  stocks:
    symbols: ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]
    start_date: "2015-01-01"
  
  economic_indicators:
    include: ["FEDFUNDS", "UNRATE", "CPI", "GDP", "RETAILSALES"]
    
  etfs:
    symbols: ["XLK", "QTEC", "VGT"]  # Tech sector ETFs
  
  news:
    sources: ["bloomberg", "reuters", "wsj", "cnbc", "yahoo-finance"]
    max_articles_per_day: 20

# Preprocessing Parameters
preprocessing:
  technical_indicators:
    - name: "SMA"
      periods: [5, 10, 20, 50, 200]
    - name: "EMA"
      periods: [12, 26]
    - name: "RSI"
      period: 14
    - name: "MACD"
      fast_period: 12
      slow_period: 26
      signal_period: 9
    - name: "BBANDS"
      period: 20
      std_dev: 2
  
  normalization:
    method: "min_max"  # Options: "min_max", "z_score"
  
  feature_selection:
    method: "recursive_feature_elimination"
    n_features: 30

# Model Parameters
model:
  type: "ensemble"  # Options: "vanilla_lstm", "bidirectional_lstm", "cnn_lstm", "ensemble"
  train_test_split: 0.8
  validation_split: 0.2
  sequence_length: 60  # 60 days of historical data
  forecast_horizon: 7  # Forecast 7 days ahead
  
  lstm:
    architecture: [128, 64, 32]  # Units in each LSTM layer
    dropout_rate: 0.2
    recurrent_dropout_rate: 0.2
    activation: "relu"
    recurrent_activation: "sigmoid"
    optimizer: "adam"
    loss: "mse"
    batch_size: 32
    epochs: 100
    early_stopping_patience: 10
    
  attention:
    enabled: true
    type: "bahdanau"  # Options: "bahdanau", "luong"
    
  ensemble:
    models: ["vanilla_lstm", "bidirectional_lstm", "cnn_lstm"]
    aggregation_method: "weighted_average"
    weights: [0.3, 0.4, 0.3]

# Evaluation Parameters
evaluation:
  metrics: ["mse", "mae", "mape", "r2", "sharpe_ratio", "max_drawdown"]
  backtesting:
    method: "walk_forward"
    initial_window: 730  # 2 years
    step_size: 30  # 1 month

# Visualization Parameters
visualization:
  theme: "dark"  # Options: "light", "dark"
  default_plots:
    - "price_vs_prediction"
    - "feature_importance"
    - "confidence_intervals"
    - "model_performance"
  dashboard:
    update_frequency: 3600  # In seconds

# Logging Configuration
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  file: "logs/market_mind.log"
  max_size: 10485760  # 10 MB
  backup_count: 5 